# Spring Boot Application Properties
spring.application.name=Organic & Natural Food E-Commerce Platform

# SQLite Database Settings (100% Zero Server Installation File)
spring.datasource.url=jdbc:sqlite:app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf & Security Settings
spring.thymeleaf.cache=false

# File Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
